# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0688f7a230d02f92be3774feb98b5fc848a63511e2bbd37b35213929954536c03f64b37d80ce6200fe1583ef45c61419f090598e7b98a76b7c2b905953c5b7dc

test:
  secret_key_base: 46898ec2ab4a5c119d95bb5b2499c21363bba83f877c0c872ebd2f11609ffb2e02d67513539fa49bc5ab9681764f7be237c0525e04894ca4ee5413cbc9fe44e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
